// WARNING:  This file was autogenerated by java-oxide.  Any changes to this file may be lost!!!
package com.github.pitchblacknights.oxidizemc.proxy.net.fabricmc.api;

@SuppressWarnings("rawtypes")
class ClientModInitializer implements net.fabricmc.api.ClientModInitializer {
    long ptr;

    private ClientModInitializer(long ptr) {
        this.ptr = ptr;
    }

    @Override
    protected void finalize() throws Throwable {
        native_finalize(this.ptr);
    }
    private native void native_finalize(long ptr);

    @Override
    public void onInitializeClient() {
        native_onInitializeClient(ptr);
    }
    private native void native_onInitializeClient(long ptr);

}
