// WARNING:  This file was autogenerated by java-oxide.  Any changes to this file may be lost!!!
package com.github.pitchblacknights.oxidizemc.proxy.net.fabricmc.api;

@SuppressWarnings("rawtypes")
class DedicatedServerModInitializer implements net.fabricmc.api.DedicatedServerModInitializer {
    long ptr;

    private DedicatedServerModInitializer(long ptr) {
        this.ptr = ptr;
    }

    @Override
    protected void finalize() throws Throwable {
        native_finalize(this.ptr);
    }
    private native void native_finalize(long ptr);

    @Override
    public void onInitializeServer() {
        native_onInitializeServer(ptr);
    }
    private native void native_onInitializeServer(long ptr);

}
