// WARNING:  This file was autogenerated by java-oxide.  Any changes to this file may be lost!!!
package com.github.pitchblacknights.oxidizemc.proxy.net.fabricmc.api;

@SuppressWarnings("rawtypes")
class ModInitializer implements net.fabricmc.api.ModInitializer {
    long ptr;

    private ModInitializer(long ptr) {
        this.ptr = ptr;
    }

    @Override
    protected void finalize() throws Throwable {
        native_finalize(this.ptr);
    }
    private native void native_finalize(long ptr);

    @Override
    public void onInitialize() {
        native_onInitialize(ptr);
    }
    private native void native_onInitialize(long ptr);

}
